In [20]:
import pandas as pd
import sqlite3
import math
import datetime 
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from IPython.core.display import display, HTML
display(HTML("<style>div.output_scroll { height: 44em; }</style>"))

In [33]:
conn = sqlite3.connect('database.db')

In [34]:
c = conn.cursor()

In [35]:
df = pd.read_csv("data_transaksi.csv")
df

,id,tanggal jual,nama customer,kota,provinsi,nama barang,merk,jenis,harga beli,harga jual,jumlah beli
0,1.0,1212122020年1月6日,Achmad Yusril,Surabaya,jawa timur,lampu depan,fdr,accessories,10000.0,15000.0,1.0
1,2.0,1212122020年1月6日,Yanuar Fitrian,Surabaya,jawa timur,lampu belakang,fdr,accessories,10000.0,15000.0,1.0
2,3.0,1212122020年1月6日,Yanuar Fitrian,Surabaya,jawa timur,kanvas rem,yanmar,rem,12000.0,16000.0,1.0
3,4.0,1212122020年1月6日,Aditya Taufiq,Surabaya,jawa timur,oli mesin,yamalube,mesin,9000.0,10000.0,1.0
4,5.0,1212122020年1月6日,Aditya Taufiq,Surabaya,jawa timur,rantai,castrol,mesin,9000.0,10000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
96,97.0,1212122020年10月6日,jasmine Meca,Surabaya,jawa timur,skok,kawasaki,skok,1747.0,2047.0,1.0
97,98.0,1212122020年10月6日,Ana bela,Surabaya,jawa timur,skok,kawasaki,skok,1748.0,2048.0,1.0
98,99.0,1212122020年10月6日,ana bela,Surabaya,jawa timur,skok,kawasaki,skok,1749.0,2049.0,1.0
99,100.0,1212122020年10月6日,rafli Ihza,Surabaya,jawa timur,skok,kawasaki,skok,1750.0,2050.0,1.0
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
kota = []
pelanggan = []
barang = []